# Generated by Django 4.2.4 on 2023-09-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='desc',
            new_name='description',
        ),
    ]
