# Generated by Django 4.2.4 on 2023-09-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_desc_menu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='vibeCheck',
            field=models.BooleanField(default=False),
        ),
    ]
