# Generated by Django 4.2.4 on 2023-09-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0011_delete_booking_delete_logger_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('datetime', models.DateTimeField(verbose_name='Date and Time of Reservation')),
                ('count', models.IntegerField(verbose_name='Number of People')),
                ('notes', models.TextField(blank=True, verbose_name='Special Requests')),
            ],
        ),
    ]
