# Generated by Django 4.2.4 on 2023-09-11 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(max_length=15, verbose_name='Contact Number')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='contact',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.person'),
        ),
    ]
