# Generated by Django 4.2.4 on 2023-09-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_person_remove_reservation_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='person',
        ),
    ]
